import { confirm, isCancel, log, password, spinner, text } from '@clack/prompts';
import { execa } from 'execa';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import pc from 'picocolors';

function requireStr(v: unknown, name: string): string {
  if (isCancel(v) || typeof v !== 'string' || !v.trim()) {
    throw new Error(`需要 ${name}`);
  }
  return v.trim();
}

async function wrangler(args: string[], env: Record<string, string>): Promise<string> {
  const { stdout } = await execa('npx', ['-y', 'wrangler', ...args], {
    env: { ...process.env, ...env },
    stdio: ['ignore', 'pipe', 'inherit'],
  });
  return stdout;
}

function parseCreateOutput(out: string, kind: 'd1' | 'kv' | 'r2'): string | null {
  if (kind === 'd1') {
    const m = out.match(/database_id\s*=\s*"([^"]+)"/);
    return m?.[1] ?? null;
  }
  if (kind === 'kv') {
    const m = out.match(/id\s*=\s*"([^"]+)"/);
    return m?.[1] ?? null;
  }
  return null;
}

export async function initCommand(): Promise<void> {
  log.info(pc.bold('将在你的 Cloudflare 账户创建 D1 / KV / R2 资源，并生成本地 .env.local。'));

  const token = requireStr(
    await password({
      message: 'Cloudflare API Token（仅保存到本机 .env.local）',
      validate: (v) => (v && v.length > 20 ? undefined : '看起来不是有效 Token'),
    }),
    'API Token',
  );
  const accountId = requireStr(await text({ message: 'Cloudflare Account ID' }), 'Account ID');
  const siteName = requireStr(
    await text({ message: '站点名（用作资源前缀）', placeholder: 'kairo', initialValue: 'kairo' }),
    'siteName',
  );

  const proceed = await confirm({ message: `在账户 ${accountId} 下创建资源？` });
  if (!proceed || isCancel(proceed)) {
    log.warn('已取消');
    return;
  }

  const env = { CLOUDFLARE_API_TOKEN: token, CLOUDFLARE_ACCOUNT_ID: accountId };

  const s = spinner();
  s.start('创建 D1 数据库…');
  const d1Out = await wrangler(['d1', 'create', `${siteName}-db`], env);
  const d1Id = parseCreateOutput(d1Out, 'd1');
  s.stop(d1Id ? `D1 已创建: ${d1Id}` : 'D1 创建完成（请从输出复制 id）');

  s.start('创建 KV 命名空间…');
  const kvOut = await wrangler(['kv', 'namespace', 'create', `${siteName}-kv`], env);
  const kvId = parseCreateOutput(kvOut, 'kv');
  s.stop(kvId ? `KV 已创建: ${kvId}` : 'KV 创建完成');

  s.start('创建 R2 存储桶…');
  await wrangler(['r2', 'bucket', 'create', `${siteName}-files`], env);
  s.stop('R2 已创建');

  // Write secrets file (gitignored)
  const envPath = join(process.cwd(), '.env.local');
  const secrets = [
    `# Auto-generated by kairo cli - DO NOT COMMIT`,
    `CLOUDFLARE_API_TOKEN=${token}`,
    `CLOUDFLARE_ACCOUNT_ID=${accountId}`,
    `KAIRO_D1_ID=${d1Id ?? ''}`,
    `KAIRO_KV_ID=${kvId ?? ''}`,
    `KAIRO_R2_BUCKET=${siteName}-files`,
    '',
  ].join('\n');
  writeFileSync(envPath, secrets, { mode: 0o600 });
  log.success(`已写入 ${envPath}（权限 0600，已在 .gitignore）`);

  log.step('下一步：');
  log.info('  1. 将 wrangler.toml 中 database_id / kv id 替换为以上值');
  log.info('  2. 执行：kairo deploy');
}
